exp_id: rvt2
tasks: all
bs: 24
num_workers: 3
epochs: 200
sample_distribution_mode: task_uniform
peract:
  # lr: 1.25e-5
  lr: 2.25e-5
  # warmup_steps: 2000
  warmup_steps: 10
  optimizer_type: lamb
  lr_cos_dec: False
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
  amp: True
  bnb: True
  lambda_weight_l2: 1e-4
rvt:
  place_with_mean: False
  img_aug: 0.0
